FROM ubuntu:18.04

RUN addgroup --gid 10001 app
RUN adduser --gid 10001 --uid 10001 \
    --home /microblog --shell /sbin/nologin \
    --disabled-password app

RUN mkdir /microblog/app
ADD app /microblog/app
ADD run.py /microblog

USER app
EXPOSE 8080
WORKDIR /app
ENTRYPOINT /app
