version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            git clone https://github.com/toliangd/projectDevSecOps02
            cd projectDevSecOps02
            docker build -t $DOCKER_USER/$IMAGE_NAME:$TAG .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/$IMAGE_NAME:$TAG
