version: 2
jobs:
  build:
    working_directory: /microblog
    docker:
      - image: python
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Add directory
          command:
            mkdir microblog
      - run:
          name: download project
          command:
            cd microblog
            git clone https://github.com/toliangd/projectDevSecOps02

      - deploy:
          command:
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
            docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}