version: 2
jobs:
  build:
    working_directory: /microblog
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker
      - run:
          name: Add directory
          command:
            mkdir /tmp/microblog
      - run:
          name: Install python git
          command:
            apt update;
            apt install -y git
      - run:
          name: Download
          command:
            cd /tmp/microblog;
            git clone https://github.com/toliangd/projectDevSecOps02;
            cd projectDevSecOps02
      - run:
          name: login
          command: |
            echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} -p --password-stdin;
      - run:
          name: build
          command: |
            docker build -t ${DOCKER_REPO} .;
            docker push ${DOCKER_REPO}
