version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            git clone https://github.com/toliangd/projectDevSecOps02.git
            cd projectDevSecOps02
            touch README.md
            echo "$DOCKER_USER/$DOCKER_REPO:0.1.${CIRCLE_BUILD_NUM}" >> README.md
            git config credential.helper 'cache --timeout=120'
            git config user.email "test@test.ru"
            git config user.name "test"
            git stash
            git checkout origin/test
            git add README.md
            git commit -m "Update via CircleCI"
            git push origin origin/test