version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            git clone https://github.com/toliangd/projectDevSecOps02
            cd projectDevSecOps02
            echo $DOCKER_USER/$DOCKER_REPO:0.1.<<pipeline.git.branch>>.${CIRCLE_BUILD_NUM}