version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            git config user.email "test@test.ru"
            git config user.name "Github Bot"
            git clone https://github.com/toliangd/projectDevSecOps02
            cd projectDevSecOps02
            docker build -t $DOCKER_USER/$DOCKER_REPO:0.1.${CIRCLE_BUILD_NUM} .
            touch README.md
            echo "$DOCKER_USER/$DOCKER_REPO:0.1.${CIRCLE_BUILD_NUM}" >> README.md
            git commit -m "add README"
            git push origin test
      
  
