version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install trivy
          command: |
            sudo apt-get install rpm wget
            wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.deb
            sudo dpkg -i trivy_0.20.0_Linux-64bit.deb
      - run:
          name: Build, scan and push Docker image
          command: |
            git clone https://github.com/toliangd/projectDevSecOps02
            cd projectDevSecOps02
            docker build -t $DOCKER_USER/$DOCKER_REPO:0.1.${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM} .
            touch rezult
            trivy --exit-code 0 --no-progress $DOCKER_USER/$DOCKER_REPO:0.1.${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM} >> rezult
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/$DOCKER_REPO:0.1.${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}
            git config credential.helper 'cache --timeout=120'
            git config user.email "circle@ci.ru"
            git config user.name "tolik"
            git add rezult
            git commit -m "Update via CircleCI"
            git push