version: 2
jobs:
  build:
    working_directory: /microblog
    docker:
      - image: python
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Add directory
          command:
            mkdir microblog
      - run:
          name: Download project
          command:
            cd microblog;
            git clone https://github.com/toliangd/projectDevSecOps02
      - run:
          name: Install docker
          command:
            curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg;
            apt update;
            apt install -y docker
      - deploy:
          command:
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
            docker build -t ${DOCKER_REPO};
            docker push ${DOCKER_REPO}