version: 2
jobs:
  build:
    working_directory: /microblog
    docker:
      - image: ubuntu:21.10
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Update
          command:
            apt update
      - run:
          name: Add directory
          command:
            mkdir microblog
      - run:
          name: Install docker
          command:
            apt install -y docker.io;
            apt install -y docker
      - run:
          name: Install python git
          command:
            apt install -y python3 pip3;
            apt install -y git
      - run:
          name: Download project
          command:
            cd microblog;
            git clone https://github.com/toliangd/projectDevSecOps02

      - deploy:
          command:
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
            docker build -t ${DOCKER_REPO} .;
            docker push ${DOCKER_REPO}