version: 2.1
jobs:
  build:
    working_directory: /microblog
    docker:
      - image: python
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Add directory
          command:
            mkdir microblog
      - run:
          name: download project
          command:
            cd microblog
            git clone https://github.com/toliangd/projectDevSecOps02

