pipeline { // В нее мы оборачиваем наш код.
    agent any
    environment {
        registry = 'tolikgd/microblog'
        registryCred = 'dockerhub'
    }

    stages {
        stage('test') {
            agent {node {label 'master'}}
            steps {
                sh 'docker info'
            }
        }
    /*    stage('Сборка, отправка и зачистка') {
            agent {node {label 'master'}}
            steps {
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                    docker.withRegistry('', registryCred) {
                    dockerImage.push()
                    }
                    sh 'docker rmi $registry:$BUILD_NUMBER'
                }
            }
        }*/
        stage('Тестирование_trivy') {
            agent {node {label 'master'}}
            steps {
                sh '''
                touch rezult-trivy-$BUILD_NUMBER
                docker run aquasec/trivy $registry:$BUILD_NUMBER >> rezult-trivy-$BUILD_NUMBER
                '''
                //sh 'CRITICAL=$(cat rezult-trivy-$BUILD_NUMBER | grep CRITICAL | wc -l); echo "$CRITICAL"; if [[ $CRITICAL -gt 0 ]]; then exit 1; fi'
            }
        }
        stage('Тестирование_grype') {
            agent {node {label 'docker'}}
            steps {
                sh '''
                touch rezult-grype-$BUILD_NUMBER
                grype $registry:$BUILD_NUMBER --scope all-layers >> rezult-grype-$BUILD_NUMBER
                '''
                //sh 'CRITICAL=$(cat rezult-grype-$BUILD_NUMBER | grep CRITICAL | wc -l); echo "$CRITICAL"; if [[ $CRITICAL -gt 0 ]]; then exit 1; fi'
            }
        }
        stage('Разветрывание') {
            steps {
                echo 'Развертывание'
            }
        }
    }
}