pipeline { // В нее мы оборачиваем наш код.
    agent any
    environment {
        registry = 'tolikgd/microblog'
        registryCred = 'dockerhub'
    }

    stages {
        stage('test') {
            steps {
                sh 'docker info'
            }
        }
        stage('Сборка, отправка и зачистка') {
            agent any
            steps {
                script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
                    docker.withRegistry('', registryCred) {
                    dockerImage.push()
                    }
                    sh 'docker rmi $registry:$BUILD_NUMBER'
                }
            }
        }
        stage('Тестирование') {
            agent any
            steps {
                sh 'docker run aquasec/trivy $registry:$BUILD_NUMBER >> rezult-$BUILD_NUMBER'
                sh 'HIGH=$(cat rezult-$BUILD_NUMBER | grep HIGH | wc -l); echo "$HIGH"; if [[ $HIGH -gt 2 ]]; then exit 1; fi'
            }
        }
        stage('Разветрывание') {
            steps {
                echo 'Развертывание'
            }
        }
    }
}